# Site settings
title: "Longx's Blog"
description: > 
    Hi, I'm Longx. Here, I mainly write about my academic life of AI.  

author: Longx
email: longxhe@gmail.com
baseurl: ""
url: "https://say-hello2y.github.io/"
twitter_username: longx
github_username:  Say-Hello2y
disqus_id: None
google_analytics_id: None

# SEO
gem:
  - jekyll-seo-tag

social:
  name: longx
  links:
    - https://github.com/Say-Hello2y
    - https://twitter.com/longxiang_he
    - https://say-hello2y.github.io/

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed

exclude: [vendor]
